import { ArrowLeft, Check, Download, MessageSquare, RotateCcw } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { StatusPill } from '../components/StatusPill';
import { assets } from '../lib/demo';

export default function AgencyAssetReview() {
  const { id }=useParams(); const asset=assets.find(a=>a.id===id)||assets[1];
  return <div className="review-workspace agency-review"><header><Link to="/app/projects/october"><ArrowLeft/> Back to project</Link><div><StatusPill status={asset.status}/><button className="icon-button"><Download/></button></div></header><main><section className="review-canvas"><div className="review-title"><div><div className="eyebrow">{asset.kind.toUpperCase()} · VERSION 2</div><h1>{asset.name}</h1></div><button className="button button-primary small"><Check size={16}/> Mark approved</button></div><div className="media-frame">{asset.kind==='video'?<video src={asset.src} controls/>:<img src={asset.src} alt=""/>}<span className="pin pin-one">1</span><span className="pin pin-two">2</span></div><div className="version-strip"><button className="active">V2 · current</button><button>V1 · changes requested</button><button><RotateCcw size={15}/> Compare</button></div></section><aside className="comment-panel"><div className="comment-tabs"><button className="active">Comments (3)</button><button>Activity</button></div><div className="thread"><div className="comment"><span className="avatar xsmall">P</span><div><b>Dr. Priya</b><time>18 min ago</time><p>Can we make the phone number larger here?</p><span className="comment-ref">Marker 1</span></div></div><div className="comment"><span className="avatar xsmall dark">A</span><div><b>You</b><time>12 min ago</time><p>Yes — I'll update this in V3.</p></div></div><div className="comment"><span className="avatar xsmall">P</span><div><b>Dr. Priya</b><time>9 min ago</time><p>The headline can move slightly upward.</p><span className="comment-ref">Marker 2</span></div></div></div><div className="comment-compose"><MessageSquare size={18}/><input placeholder="Reply to feedback…"/><button>Send</button></div></aside></main></div>;
}
