import { Check, Copy, Send } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Topbar } from '../components/Topbar';
import { assets } from '../lib/demo';

export default function ApprovalNew() {
  const [sent,setSent]=useState(false); const [selected,setSelected]=useState<string[]>(assets.slice(0,4).map(a=>a.id));
  if(sent) return <><Topbar/><div className="page-pad narrow"><div className="success-card"><div className="success-icon"><Check/></div><div className="eyebrow warm">APPROVAL REQUEST CREATED</div><h1>Ready for client review.</h1><p>Send this secure link by email, WhatsApp, Slack or anywhere you already talk to the client.</p><div className="copy-box"><span>https://approveflow.com/review/demo</span><button><Copy size={16}/> Copy</button></div><div className="form-actions"><Link className="button button-ghost" to="/app/dashboard">Back to dashboard</Link><Link className="button button-primary" to="/review/demo">Open client review</Link></div></div></div></>;
  return <><Topbar/><div className="page-pad approval-layout"><section><div className="eyebrow">APPROVAL REQUEST</div><h1>Send for client approval</h1><p>Pick what the client should review and create one secure link.</p><div className="panel form-panel"><label>Client<select><option>SmileCraft Dental</option></select></label><label>Project<select><option>October Content</option></select></label><label>Reviewer email<input defaultValue="priya@smilecraftdental.com"/></label><label>Message<textarea defaultValue="Hi Priya, here is the October content. Please mark any changes directly on the creative and approve the items that are ready."/></label><div className="form-grid"><label>Review requested by<input type="date"/></label><label>Reminder schedule<select><option>24h, 72h, then creator</option><option>Every 3 days</option><option>Off</option></select></label></div><label className="check"><input type="checkbox" defaultChecked/> Email the reviewer now</label><button className="button button-primary full" onClick={()=>setSent(true)}><Send size={16}/> Send approval request</button></div></section><aside className="panel"><h2>Assets</h2><p className="subtle">{selected.length} selected</p><div className="select-assets">{assets.map(a=><label key={a.id} className={selected.includes(a.id)?'select-asset selected':'select-asset'}><input type="checkbox" checked={selected.includes(a.id)} onChange={()=>setSelected(x=>x.includes(a.id)?x.filter(i=>i!==a.id):[...x,a.id])}/>{a.kind==='video'?<video src={a.src} muted/>:<img src={a.src} alt=""/>}<div><b>{a.name}</b><span>{a.kind}</span></div></label>)}</div></aside></div></>;
}
