import { Check, ChevronLeft, ChevronRight, MessageSquare, MousePointer2, Pencil, Play, Send, Square, X } from 'lucide-react';
import { MouseEvent, useMemo, useRef, useState } from 'react';
import { Brand } from '../components/Brand';
import { assets } from '../lib/demo';
import type { Annotation } from '../lib/types';

function ImageReviewer({ src }: { src: string }) {
  const [annotations, setAnnotations] = useState<Annotation[]>([
    { id:'a1', x:.73, y:.32, text:'Can we make this text larger?', author:'Dr. Priya' },
    { id:'a2', x:.38, y:.66, text:'Please use a darker blue here.', author:'Dr. Priya' }
  ]);
  const [marking, setMarking] = useState(false); const [draft,setDraft]=useState(''); const [pending,setPending]=useState<{x:number;y:number}|null>(null);
  const click = (e: MouseEvent<HTMLDivElement>) => { if(!marking) return; const r=e.currentTarget.getBoundingClientRect(); setPending({x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}); setDraft(''); };
  const save = () => { if(!pending || !draft.trim()) return; setAnnotations(v=>[...v,{id:crypto.randomUUID(),...pending,text:draft.trim(),author:'Dr. Priya'}]); setPending(null); setMarking(false); };
  return <div className="client-review-grid"><section><div className={marking?'annotatable-media marking':'annotatable-media'} onClick={click}><img src={src} alt="Creative under review"/>{annotations.map((a,i)=><button key={a.id} className="annotation-pin" style={{left:`${a.x*100}%`,top:`${a.y*100}%`}}>{i+1}</button>)}{pending&&<span className="annotation-pin pending" style={{left:`${pending.x*100}%`,top:`${pending.y*100}%`}}>{annotations.length+1}</span>}</div><div className="annotation-toolbar"><button className={marking?'active':''} onClick={()=>setMarking(v=>!v)}><MousePointer2 size={16}/> Mark on image</button><button><Square size={16}/> Rectangle</button><button><Pencil size={16}/> Draw</button><span>Click directly on the area that needs changing.</span></div></section><aside className="client-comments"><h3>Feedback ({annotations.length})</h3>{annotations.map((a,i)=><div className="feedback-item" key={a.id}><span>{i+1}</span><div><b>{a.author}</b><p>{a.text}</p></div></div>)}{pending&&<div className="annotation-draft"><b>Marker {annotations.length+1}</b><textarea autoFocus value={draft} onChange={e=>setDraft(e.target.value)} placeholder="What should change here?"/><div><button onClick={()=>setPending(null)}>Cancel</button><button className="button button-primary small" onClick={save}>Add feedback</button></div></div>}</aside></div>;
}


function CarouselReviewer({ src }: { src: string }) {
  const slides = [src, assets[0].src, assets[4].src, assets[5].src];
  const [slide, setSlide] = useState(0);
  return <div className="carousel-review"><div className="carousel-strip">{slides.map((s,i)=><button key={s+i} className={i===slide?'active':''} onClick={()=>setSlide(i)}><img src={s} alt=""/><span>Slide {i+1}</span></button>)}</div><div className="slide-label">Carousel · Slide {slide+1} of {slides.length} · feedback is attached to this slide</div><ImageReviewer src={slides[slide]}/></div>;
}

function VideoReviewer({ src }: { src: string }) {
  const ref=useRef<HTMLVideoElement>(null); const [comments,setComments]=useState([{t:6,text:'Can we shorten this opening?'},{t:12,text:'Can we use the brighter tagline here?'},{t:18,text:'This transition feels too fast.'}]); const [text,setText]=useState(''); const [range,setRange]=useState<[number,number]>([0,0]);
  const current=Math.floor(ref.current?.currentTime||0); const add=()=>{ if(!text.trim()) return; setComments(v=>[...v,{t:Math.floor(ref.current?.currentTime||0),text:text.trim()}]); setText(''); };
  return <div className="client-review-grid video-review-grid"><section><div className="video-stage"><video ref={ref} src={src} controls playsInline/><button className="video-overlay"><Play/></button></div><div className="range-tools"><b>Select a portion</b><label>From <input type="number" min="0" value={range[0]} onChange={e=>setRange([+e.target.value,range[1]])}/>s</label><label>To <input type="number" min="0" value={range[1]} onChange={e=>setRange([range[0],+e.target.value])}/>s</label><span>or pause the video and comment at the current timestamp.</span></div><div className="timeline-demo"><div className="timeline-track"><span className="selection" style={{left:'28%',width:'22%'}}/><span className="marker" style={{left:'18%'}}/><span className="marker two" style={{left:'44%'}}/><span className="marker three" style={{left:'70%'}}/></div><div className="timeline-thumbs">{Array.from({length:8}).map((_,i)=><div key={i}/>)}</div></div></section><aside className="client-comments"><h3>Timestamp comments ({comments.length})</h3>{comments.map((c,i)=><button className="timestamp-comment" key={`${c.t}-${i}`} onClick={()=>{if(ref.current){ref.current.currentTime=c.t;ref.current.play();}}}><span>00:{String(c.t).padStart(2,'0')}</span><p>{c.text}</p></button>)}<div className="timestamp-compose"><span>00:{String(current).padStart(2,'0')}</span><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Add a comment at this point…"/><button className="button button-primary small" onClick={add}><Send size={14}/> Add</button></div></aside></div>;
}

export default function ClientReview() {
  const reviewAssets=useMemo(()=>assets.slice(0,5),[]); const [index,setIndex]=useState(1); const [decision,setDecision]=useState<'idle'|'approve'|'changes'>('idle'); const asset=reviewAssets[index];
  return <div className="client-review-page"><header><Brand compact/><div className="review-brand-info"><b>October Content</b><span>for SmileCraft Dental · {index+1} of {reviewAssets.length}</span></div><div className="reviewer-chip">Reviewing as Dr. Priya</div></header><div className="review-progress"><span style={{width:`${((index+1)/reviewAssets.length)*100}%`}}/></div><main><div className="client-review-title"><div><div className="eyebrow">{asset.kind.toUpperCase()}</div><h1>{asset.name}</h1><p>{asset.caption}</p></div><div className="nav-arrows"><button disabled={index===0} onClick={()=>setIndex(i=>i-1)}><ChevronLeft/></button><span>{index+1} / {reviewAssets.length}</span><button disabled={index===reviewAssets.length-1} onClick={()=>setIndex(i=>i+1)}><ChevronRight/></button></div></div>{asset.kind==='video'?<VideoReviewer src={asset.src}/>:asset.kind==='carousel'?<CarouselReviewer src={asset.src}/>:<ImageReviewer src={asset.src}/>}</main><footer className="client-review-actions"><div><MessageSquare size={18}/><span>Leave feedback directly on the creative before requesting changes.</span></div><div><button className="button request" onClick={()=>setDecision('changes')}><X size={17}/> Request changes</button><button className="button approve" onClick={()=>setDecision('approve')}><Check size={18}/> Approve</button></div></footer>{decision!=='idle'&&<div className="decision-modal"><div className="decision-card"><button className="close" onClick={()=>setDecision('idle')}><X/></button>{decision==='approve'?<><div className="success-icon"><Check/></div><h2>Approve this content?</h2><p>This records your approval for the current version of the creative and caption.</p><button className="button approve full" onClick={()=>{setDecision('idle'); if(index<reviewAssets.length-1)setIndex(i=>i+1);}}>Confirm approval</button></>:<><div className="change-icon"><Pencil/></div><h2>Send your requested changes?</h2><p>Your image markers and timestamp comments will be sent together to the agency.</p><button className="button request full" onClick={()=>{setDecision('idle'); if(index<reviewAssets.length-1)setIndex(i=>i+1);}}>Send feedback</button></>}</div></div>}</div>;
}
