import { Check, CreditCard, Mail, Palette, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { PageHeader } from '../components/PageHeader';
import { Topbar } from '../components/Topbar';

export function WorkspaceSettings(){return <><Topbar/><div className="page-pad narrow"><PageHeader eyebrow="SETTINGS" title="Workspace"/><form className="panel form-panel"><label>Agency name<input defaultValue="Pixel Agency"/></label><label>Reply-to email<input defaultValue="hello@pixelagency.com"/></label><label>Timezone<select defaultValue="Asia/Kolkata"><option>Asia/Kolkata</option><option>America/New_York</option><option>Europe/London</option></select></label><label>Branding<div className="branding-box"><div className="brand-preview"><span className="brand-mark smallmark">✓</span><b>Pixel Agency</b></div><div><button type="button" className="button button-ghost small"><Palette size={15}/> Change logo & colors</button></div></div></label><label>Default reminder schedule<select><option>24 hours, 72 hours, then notify me</option><option>Every 3 days</option><option>Off</option></select></label><button className="button button-primary">Save changes</button></form></div></>}

export function NotificationSettings(){const [checks,setChecks]=useState([true,true,true,true,false]); const labels=['Client approves content','Client requests changes','Client leaves a comment','Approval becomes overdue','Client merely views content']; return <><Topbar/><div className="page-pad narrow"><PageHeader eyebrow="SETTINGS" title="Notifications"/><div className="panel form-panel"><div className="settings-intro"><span className="settings-icon"><Mail/></span><div><h2>Email me when…</h2><p>Keep only the alerts that help you act.</p></div></div>{labels.map((label,i)=><label className="toggle-row" key={label}><div><b>{label}</b><span>{i===4?'Usually noisy; off by default.':'Sent to your workspace notification email.'}</span></div><input type="checkbox" checked={checks[i]} onChange={()=>setChecks(v=>v.map((x,j)=>j===i?!x:x))}/></label>)}<button className="button button-primary">Save preferences</button></div></div></>}

export function BillingSettings(){return <><Topbar/><div className="page-pad"><PageHeader eyebrow="BILLING" title="Simple plans with storage guardrails"/><div className="plan-grid"><Plan name="Solo" price="₹599" storage="10 GB" items={['5 active clients','Email reminders','Image + video review']}/><Plan featured name="Freelancer" price="₹999" storage="50 GB" items={['20 active clients','White-label logo','50 GB included storage','Priority review links']}/><Plan name="Agency" price="₹1,599" storage="150 GB" items={['Team members','Custom branding','150 GB storage','Higher upload limits']}/></div><div className="panel billing-note"><ShieldCheck/><div><h3>Razorpay billing only</h3><p>Subscription state is updated from verified Razorpay webhooks. Browser success callbacks are never treated as the source of truth.</p></div></div></div></>}

function Plan({name,price,storage,items,featured=false}:{name:string;price:string;storage:string;items:string[];featured?:boolean}){return <article className={featured?'plan-card featured':'plan-card'}>{featured&&<span className="plan-badge">POPULAR</span>}<div className="eyebrow">{name}</div><h2>{price}<small>/month</small></h2><p>{storage} included storage</p><ul>{items.map(i=><li key={i}><Check size={15}/>{i}</li>)}</ul><button className={featured?'button button-primary full':'button button-ghost full'}><CreditCard size={16}/> Choose {name}</button></article>}
